# Generated by Django 3.2.8 on 2021-10-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='student',
            new_name='students',
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
